development:
  adapter: postgresql
  database: chat
  username: chat
  password: chat
  encoding: unicode
  pool: 5

production:
  adapter: postgresql
  database: chat
  username: chat
  password: chat
  encoding: unicode
  pool: 5