development:
  adapter: postgresql
  database: chat
  username: postgres
  password: postgres
  encoding: unicode
  pool: 5

production:
  adapter: postgresql
  database: chat
  username: postgres
  password: postgres
  encoding: unicode
  pool: 5